apiVersion: v1
kind: PersistentVolume
metadata:
  name: pvnew
spec:
  storageClassName: storageforpvandpvc
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 2Gi
  hostPath:
    path: /data/pv001

