apiVersion: apps/v1
kind: Deployment 
metadata:
  name: apachedeployment
spec:
  replicas: 3
  selector:
    matchLabels:
      name: apache 
  template:
    metadata:
      name: apachepod
      labels:
        name: apache
    spec:
      containers:
        - name: apachecontainer
          resources:
            limits:
              memory: "500Mi"
              cpu: "500m"
          image: httpd:2.4
          ports:
            - containerPort: 80

          
