apiVersion: apps/v1 
kind: Deployment 
metadata: 
  name: nginxdeployment
spec:
  replicas: 1
  selector:
    matchLabels: 
      name: nginxapp 
  template: 
    metadata: 
      name: nginxpod
      labels:
        name: nginxapp
    spec:
      containers:
        - name: nginxcontainer
          image: nginx:latest 
          ports: 
            - containerPort: 80
          resources:
            limits:
              memory: "500Mi"
              cpu: "500m"
