apiVersion: apps/v1
kind: Deployment 
metadata: 
  name: nginxdeployment
spec:
  replicas: 3
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  selector:
    matchLabels:
      name: app
  template:
    metadata:
      name: nginxpod
      labels: 
        name: app
    spec:
      containers:
        - name: nginxcontainer
          image: nginx:latest 
          ports:
            - containerPort: 80
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          
