apiVersion: v1 
kind: Service 
metadata: 
  name: nginxservice
  labels: 
    name: nginxapp
spec:
  selector: 
    name: nginxapp
  type: NodePort
  ports:
    - port: 8080
      targetPort: 80
      nodePort: 31234

