apiVersion: v1
kind: Pod
metadata:
  name: nginxpod
spec:
  containers:
    - name: nginxcontainer
      ports:
        - containerPort: 80
      image: nginx:latest
      resources:
        limits:
          memory: "128Mi"
          cpu: "500m"
      volumeMounts:
        - name: nginxvolume
          mountPath: /tmp
  volumes:
    - name: nginxvolume
      emptyDir: {}


