- hosts: web
  remote_user: root 
  become: true 
  tasks:
    - name: install nginx
      yum: 
        name: nginx
        state: installed
    - name: remove nginx
      yum: 
        name: nginx
        state: removed